#!/bin/bash
sudo modprobe -r lp
sudo chmod 777 /dev/parport0
read -p "subjectID: " subID
read -p "[c] calibration, [v] validation, [t] training or [d] decoding? " mode

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )" #${BASH_SOURCE[0]} finds path to currently executing script and >/dev/null discards any output from cd
echo $dir

#########################################################################

if [ "$mode" = "c" ]
	then
 	echo "
----------------------------------
----> Calibration Mode selected <-----
----------------------------------
"

# Open GDF and log files
datetime=$(date +%Y%m%d%H%M%S)
basename=$dir/data/"e"$subID"_"$datetime"_calibration"
foldername=$dir/data/"e"$subID"_"$(date +%Y%m%d) 
gdffilename=$basename".gdf"
logfilename=$basename".log"

mkdir $basename/

echo $gdffilename
echo $logfilename
cl_rpc openxdf $gdffilename $logfilename ""

sleep 3
python3 ./visualInterface/calibration.py

# Close the GDF file
sleep 3
cl_rpc closexdf
mv $basename.* $basename/

mkdir -p $foldername
mv $basename $foldername

#########################################################################
elif [ "$mode" = "v" ]
 	then
 	echo "
----------------------------------
----> Validation Mode selected <-----
----------------------------------
"

# Open GDF and log files
datetime=$(date +%Y%m%d%H%M%S)
basename=$dir/data/"e"$subID"_"$datetime"_validation"
foldername=$dir/data/"e"$subID"_"$(date +%Y%m%d) 
gdffilename=$basename".gdf"
logfilename=$basename".log"

mkdir $basename/

echo $gdffilename
echo $logfilename
cl_rpc openxdf $gdffilename $logfilename ""

# Run Python Interface
sleep 3
python3 ./visualInterface/distractor_task_validation.py "$basename"

# Close the GDF file
sleep 3
cl_rpc closexdf
mv $basename.* $basename/

mkdir -p $foldername
mv $basename $foldername

#########################################################################
elif [ "$mode" = "t" ]
 	then
 	echo "
----------------------------------
----> Training Mode selected <-----
----------------------------------
"

# Open GDF and log files
datetime=$(date +%Y%m%d%H%M%S)
basename=$dir/data/"e"$subID"_"$datetime"_training"
foldername=$dir/data/"e"$subID"_"$(date +%Y%m%d) 
gdffilename=$basename".gdf"
logfilename=$basename".log"

mkdir $basename/

echo $gdffilename
echo $logfilename
cl_rpc openxdf $gdffilename $logfilename ""

# Run Python Interface
sleep 3
python3 ./visualInterface/distractor_task_training.py "$basename"

# Close the GDF file
sleep 3
cl_rpc closexdf
mv $basename.* $basename/

mkdir -p $foldername
mv $basename $foldername

#########################################################################

elif [ "$mode" = "d" ]
	then
 	echo "
----------------------------------
----> Decoding Mode selected <-----
----------------------------------
"
# Open GDF and log files
datetime=$(date +%Y%m%d%H%M%S)
basename=$dir/data/"e"$subID"_"$datetime"_decoding"
foldername=$dir/data/"e"$subID"_"$(date +%Y%m%d) 
gdffilename=$basename".gdf"
logfilename=$basename".log"

mkdir $basename/

echo $gdffilename
echo $logfilename
cl_rpc openxdf $gdffilename $logfilename ""

# Run ndf file
sleep 2
# gnome-terminal -e "./matlabLauncher" --title "Distractor Detection" #gnome-terminal -e executes command in quotes in new terminal window
gnome-terminal --title "Distractor Detection" -- bash -c "./matlabLauncher; echo 'Press Enter to close...'; read"

# Run python script
sleep 20
python3 ./visualInterface/distractor_task_decoding.py "$basename"

# Close the GDF file
sleep 3
cl_rpc closexdf
mv $basename.* $basename/

mkdir -p $foldername
mv $basename $foldername

fi #ends the if statement 