from python_client import Trigger
import time
time.sleep(5)
HWTrigger = Trigger('ARDUINO')
HWTrigger.init(50)
time.sleep(1)
HWTrigger.signal(1)
time.sleep(1)
# HWTrigger.signal(2)
# time.sleep(1)
# HWTrigger.signal(4)
# time.sleep(1)
# HWTrigger.signal(8)
# time.sleep(1)
# HWTrigger.signal(16)
# time.sleep(1)
# HWTrigger.signal(32)
# time.sleep(1)
# HWTrigger.signal(64)
# time.sleep(1)
# HWTrigger.signal(128)
